//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidateAddIn.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request_BU_Sistema_Plaza_FechaValDC", Namespace="http://abaseguros.com")]
    [System.SerializableAttribute()]
    public partial class Request_BU_Sistema_Plaza_FechaValDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BusinessUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPlazaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaValidacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BusinessUnit {
            get {
                return this.BusinessUnitField;
            }
            set {
                if ((this.BusinessUnitField.Equals(value) != true)) {
                    this.BusinessUnitField = value;
                    this.RaisePropertyChanged("BusinessUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSistema {
            get {
                return this.idSistemaField;
            }
            set {
                if ((this.idSistemaField.Equals(value) != true)) {
                    this.idSistemaField = value;
                    this.RaisePropertyChanged("idSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int idPlaza {
            get {
                return this.idPlazaField;
            }
            set {
                if ((this.idPlazaField.Equals(value) != true)) {
                    this.idPlazaField = value;
                    this.RaisePropertyChanged("idPlaza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime FechaValidacion {
            get {
                return this.FechaValidacionField;
            }
            set {
                if ((this.FechaValidacionField.Equals(value) != true)) {
                    this.FechaValidacionField = value;
                    this.RaisePropertyChanged("FechaValidacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObtieneBitacoraCollectionDC", Namespace="http://abaseguros.com", ItemName="ObtieneBitacoraDC")]
    [System.SerializableAttribute()]
    public class ObtieneBitacoraCollectionDC : System.Collections.Generic.List<ValidateAddIn.ServiceReference.ObtieneBitacoraDC> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtieneBitacoraDC", Namespace="http://abaseguros.com")]
    [System.SerializableAttribute()]
    public partial class ObtieneBitacoraDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double idMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idValidacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double idMensaje {
            get {
                return this.idMensajeField;
            }
            set {
                if ((this.idMensajeField.Equals(value) != true)) {
                    this.idMensajeField = value;
                    this.RaisePropertyChanged("idMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> idValidacion {
            get {
                return this.idValidacionField;
            }
            set {
                if ((this.idValidacionField.Equals(value) != true)) {
                    this.idValidacionField = value;
                    this.RaisePropertyChanged("idValidacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetJournalValidationDC", Namespace="http://abaseguros.com")]
    [System.SerializableAttribute()]
    public partial class GetJournalValidationDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ValidateAddIn.ServiceReference.Header HeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ValidateAddIn.ServiceReference.Detail[] AccountingDetailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ValidateAddIn.ServiceReference.Header Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public ValidateAddIn.ServiceReference.Detail[] AccountingDetail {
            get {
                return this.AccountingDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountingDetailField, value) != true)) {
                    this.AccountingDetailField = value;
                    this.RaisePropertyChanged("AccountingDetail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Header", Namespace="http://abaseguros.com")]
    [System.SerializableAttribute()]
    public partial class Header : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime AccountingDateField;
        
        private int SourceSystemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BranchField;
        
        private int BusinessUnitField;
        
        private string RecordTypeField;
        
        private int RegisterCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime AccountingDate {
            get {
                return this.AccountingDateField;
            }
            set {
                if ((this.AccountingDateField.Equals(value) != true)) {
                    this.AccountingDateField = value;
                    this.RaisePropertyChanged("AccountingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SourceSystemId {
            get {
                return this.SourceSystemIdField;
            }
            set {
                if ((this.SourceSystemIdField.Equals(value) != true)) {
                    this.SourceSystemIdField = value;
                    this.RaisePropertyChanged("SourceSystemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Branch {
            get {
                return this.BranchField;
            }
            set {
                if ((this.BranchField.Equals(value) != true)) {
                    this.BranchField = value;
                    this.RaisePropertyChanged("Branch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int BusinessUnit {
            get {
                return this.BusinessUnitField;
            }
            set {
                if ((this.BusinessUnitField.Equals(value) != true)) {
                    this.BusinessUnitField = value;
                    this.RaisePropertyChanged("BusinessUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string RecordType {
            get {
                return this.RecordTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordTypeField, value) != true)) {
                    this.RecordTypeField = value;
                    this.RaisePropertyChanged("RecordType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int RegisterCount {
            get {
                return this.RegisterCountField;
            }
            set {
                if ((this.RegisterCountField.Equals(value) != true)) {
                    this.RegisterCountField = value;
                    this.RaisePropertyChanged("RegisterCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Detail", Namespace="http://abaseguros.com")]
    [System.SerializableAttribute()]
    public partial class Detail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RegisterIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LedgerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatingUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MccField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunctionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AffiliateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LineDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginalCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OriginalAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistributionChannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JrnlLnRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PoliceYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MonetaryAmountField;
        
        private string TransactionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PsAccountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RegisterId {
            get {
                return this.RegisterIdField;
            }
            set {
                if ((this.RegisterIdField.Equals(value) != true)) {
                    this.RegisterIdField = value;
                    this.RaisePropertyChanged("RegisterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Ledger {
            get {
                return this.LedgerField;
            }
            set {
                if ((object.ReferenceEquals(this.LedgerField, value) != true)) {
                    this.LedgerField = value;
                    this.RaisePropertyChanged("Ledger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string OperatingUnit {
            get {
                return this.OperatingUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatingUnitField, value) != true)) {
                    this.OperatingUnitField = value;
                    this.RaisePropertyChanged("OperatingUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string DepId {
            get {
                return this.DepIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DepIdField, value) != true)) {
                    this.DepIdField = value;
                    this.RaisePropertyChanged("DepId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Mcc {
            get {
                return this.MccField;
            }
            set {
                if ((object.ReferenceEquals(this.MccField, value) != true)) {
                    this.MccField = value;
                    this.RaisePropertyChanged("Mcc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Function {
            get {
                return this.FunctionField;
            }
            set {
                if ((object.ReferenceEquals(this.FunctionField, value) != true)) {
                    this.FunctionField = value;
                    this.RaisePropertyChanged("Function");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Affiliate {
            get {
                return this.AffiliateField;
            }
            set {
                if ((object.ReferenceEquals(this.AffiliateField, value) != true)) {
                    this.AffiliateField = value;
                    this.RaisePropertyChanged("Affiliate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string LineDescription {
            get {
                return this.LineDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.LineDescriptionField, value) != true)) {
                    this.LineDescriptionField = value;
                    this.RaisePropertyChanged("LineDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string OriginalCurrency {
            get {
                return this.OriginalCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalCurrencyField, value) != true)) {
                    this.OriginalCurrencyField = value;
                    this.RaisePropertyChanged("OriginalCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public decimal OriginalAmount {
            get {
                return this.OriginalAmountField;
            }
            set {
                if ((this.OriginalAmountField.Equals(value) != true)) {
                    this.OriginalAmountField = value;
                    this.RaisePropertyChanged("OriginalAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string DistributionChannel {
            get {
                return this.DistributionChannelField;
            }
            set {
                if ((object.ReferenceEquals(this.DistributionChannelField, value) != true)) {
                    this.DistributionChannelField = value;
                    this.RaisePropertyChanged("DistributionChannel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string JrnlLnRef {
            get {
                return this.JrnlLnRefField;
            }
            set {
                if ((object.ReferenceEquals(this.JrnlLnRefField, value) != true)) {
                    this.JrnlLnRefField = value;
                    this.RaisePropertyChanged("JrnlLnRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string ProjectId {
            get {
                return this.ProjectIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectIdField, value) != true)) {
                    this.ProjectIdField = value;
                    this.RaisePropertyChanged("ProjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public System.Nullable<int> Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public System.Nullable<int> PoliceYear {
            get {
                return this.PoliceYearField;
            }
            set {
                if ((this.PoliceYearField.Equals(value) != true)) {
                    this.PoliceYearField = value;
                    this.RaisePropertyChanged("PoliceYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public System.Nullable<decimal> MonetaryAmount {
            get {
                return this.MonetaryAmountField;
            }
            set {
                if ((this.MonetaryAmountField.Equals(value) != true)) {
                    this.MonetaryAmountField = value;
                    this.RaisePropertyChanged("MonetaryAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public string TransactionCode {
            get {
                return this.TransactionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionCodeField, value) != true)) {
                    this.TransactionCodeField = value;
                    this.RaisePropertyChanged("TransactionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public string AltAccount {
            get {
                return this.AltAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AltAccountField, value) != true)) {
                    this.AltAccountField = value;
                    this.RaisePropertyChanged("AltAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public string PsAccount {
            get {
                return this.PsAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.PsAccountField, value) != true)) {
                    this.PsAccountField = value;
                    this.RaisePropertyChanged("PsAccount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="GetJournalValidationCollectionDC", Namespace="http://abaseguros.com", ItemName="ErrorDC")]
    [System.SerializableAttribute()]
    public class GetJournalValidationCollectionDC : System.Collections.Generic.List<ValidateAddIn.ServiceReference.ErrorDC> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorDC", Namespace="http://abaseguros.com")]
    [System.SerializableAttribute()]
    public partial class ErrorDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProcessIdField;
        
        private string ErrorDescriptionField;
        
        private int RecordIdField;
        
        private int ValidationIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProcessId {
            get {
                return this.ProcessIdField;
            }
            set {
                if ((this.ProcessIdField.Equals(value) != true)) {
                    this.ProcessIdField = value;
                    this.RaisePropertyChanged("ProcessId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string ErrorDescription {
            get {
                return this.ErrorDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescriptionField, value) != true)) {
                    this.ErrorDescriptionField = value;
                    this.RaisePropertyChanged("ErrorDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int RecordId {
            get {
                return this.RecordIdField;
            }
            set {
                if ((this.RecordIdField.Equals(value) != true)) {
                    this.RecordIdField = value;
                    this.RaisePropertyChanged("RecordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int ValidationId {
            get {
                return this.ValidationIdField;
            }
            set {
                if ((this.ValidationIdField.Equals(value) != true)) {
                    this.ValidationIdField = value;
                    this.RaisePropertyChanged("ValidationId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://abaseguros.com", ConfigurationName="ServiceReference.ValidacionesSiacServiceContract")]
    public interface ValidacionesSiacServiceContract {
        
        // CODEGEN: Generating message contract since the wrapper name (ObtieneBitacoraRequest) of message ObtieneBitacoraRequest does not match the default value (ObtieneBitacora)
        [System.ServiceModel.OperationContractAttribute(Action="ObtieneBitacora", ReplyAction="http://abaseguros.com/ValidacionesSiacServiceContract/ObtieneBitacoraResponse")]
        ValidateAddIn.ServiceReference.ObtieneBitacoraResponse ObtieneBitacora(ValidateAddIn.ServiceReference.ObtieneBitacoraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ObtieneBitacora", ReplyAction="http://abaseguros.com/ValidacionesSiacServiceContract/ObtieneBitacoraResponse")]
        System.Threading.Tasks.Task<ValidateAddIn.ServiceReference.ObtieneBitacoraResponse> ObtieneBitacoraAsync(ValidateAddIn.ServiceReference.ObtieneBitacoraRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ObtieneBitacoraRequest) of message ObtieneBitacoraRequest does not match the default value (ObtieneBitacoraHistorial)
        [System.ServiceModel.OperationContractAttribute(Action="ObtieneBitacoraHistorial", ReplyAction="http://abaseguros.com/ValidacionesSiacServiceContract/ObtieneBitacoraHistorialRes" +
            "ponse")]
        ValidateAddIn.ServiceReference.ObtieneBitacoraHistorialResponse ObtieneBitacoraHistorial(ValidateAddIn.ServiceReference.ObtieneBitacoraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ObtieneBitacoraHistorial", ReplyAction="http://abaseguros.com/ValidacionesSiacServiceContract/ObtieneBitacoraHistorialRes" +
            "ponse")]
        System.Threading.Tasks.Task<ValidateAddIn.ServiceReference.ObtieneBitacoraHistorialResponse> ObtieneBitacoraHistorialAsync(ValidateAddIn.ServiceReference.ObtieneBitacoraRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ObtieneBitacoraReporteRequest) of message ObtieneBitacoraReporteRequest does not match the default value (ObtieneBitacoraCargaReporte)
        [System.ServiceModel.OperationContractAttribute(Action="ObtieneBitacoraCargaReporte", ReplyAction="http://abaseguros.com/ValidacionesSiacServiceContract/ObtieneBitacoraCargaReporte" +
            "Response")]
        ValidateAddIn.ServiceReference.ObtieneBitacoraResponse ObtieneBitacoraCargaReporte(ValidateAddIn.ServiceReference.ObtieneBitacoraReporteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ObtieneBitacoraCargaReporte", ReplyAction="http://abaseguros.com/ValidacionesSiacServiceContract/ObtieneBitacoraCargaReporte" +
            "Response")]
        System.Threading.Tasks.Task<ValidateAddIn.ServiceReference.ObtieneBitacoraResponse> ObtieneBitacoraCargaReporteAsync(ValidateAddIn.ServiceReference.ObtieneBitacoraReporteRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetJournalValidationRequest) of message GetJournalValidationRequest does not match the default value (GetJournalValidation)
        [System.ServiceModel.OperationContractAttribute(Action="AccountingInformation", ReplyAction="http://abaseguros.com/ValidacionesSiacServiceContract/GetJournalValidationRespons" +
            "e")]
        ValidateAddIn.ServiceReference.GetJournalValidationResponse GetJournalValidation(ValidateAddIn.ServiceReference.GetJournalValidationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AccountingInformation", ReplyAction="http://abaseguros.com/ValidacionesSiacServiceContract/GetJournalValidationRespons" +
            "e")]
        System.Threading.Tasks.Task<ValidateAddIn.ServiceReference.GetJournalValidationResponse> GetJournalValidationAsync(ValidateAddIn.ServiceReference.GetJournalValidationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtieneBitacoraRequest", WrapperNamespace="http://abaseguros.com", IsWrapped=true)]
    public partial class ObtieneBitacoraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://abaseguros.com", Order=0)]
        public ValidateAddIn.ServiceReference.Request_BU_Sistema_Plaza_FechaValDC Request_BU_Sistema_Plaza_FechaVal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://abaseguros.com", Order=1)]
        public int idTipoValidacion;
        
        public ObtieneBitacoraRequest() {
        }
        
        public ObtieneBitacoraRequest(ValidateAddIn.ServiceReference.Request_BU_Sistema_Plaza_FechaValDC Request_BU_Sistema_Plaza_FechaVal, int idTipoValidacion) {
            this.Request_BU_Sistema_Plaza_FechaVal = Request_BU_Sistema_Plaza_FechaVal;
            this.idTipoValidacion = idTipoValidacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtieneBitacoraResponse", WrapperNamespace="http://abaseguros.com", IsWrapped=true)]
    public partial class ObtieneBitacoraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://abaseguros.com", Order=0)]
        public ValidateAddIn.ServiceReference.ObtieneBitacoraCollectionDC ObtieneBitacora;
        
        public ObtieneBitacoraResponse() {
        }
        
        public ObtieneBitacoraResponse(ValidateAddIn.ServiceReference.ObtieneBitacoraCollectionDC ObtieneBitacora) {
            this.ObtieneBitacora = ObtieneBitacora;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtieneBitacoraHistorialResponse", WrapperNamespace="http://abaseguros.com", IsWrapped=true)]
    public partial class ObtieneBitacoraHistorialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://abaseguros.com", Order=0)]
        public ValidateAddIn.ServiceReference.ObtieneBitacoraCollectionDC ObtieneBitacora;
        
        public ObtieneBitacoraHistorialResponse() {
        }
        
        public ObtieneBitacoraHistorialResponse(ValidateAddIn.ServiceReference.ObtieneBitacoraCollectionDC ObtieneBitacora) {
            this.ObtieneBitacora = ObtieneBitacora;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtieneBitacoraReporteRequest", WrapperNamespace="http://abaseguros.com", IsWrapped=true)]
    public partial class ObtieneBitacoraReporteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://abaseguros.com", Order=0)]
        public int BusinessUnit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://abaseguros.com", Order=1)]
        public System.DateTime Fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://abaseguros.com", Order=2)]
        public int TipoArchivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://abaseguros.com", Order=3)]
        public int TipoValidacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://abaseguros.com", Order=4)]
        public string Usuario;
        
        public ObtieneBitacoraReporteRequest() {
        }
        
        public ObtieneBitacoraReporteRequest(int BusinessUnit, System.DateTime Fecha, int TipoArchivo, int TipoValidacion, string Usuario) {
            this.BusinessUnit = BusinessUnit;
            this.Fecha = Fecha;
            this.TipoArchivo = TipoArchivo;
            this.TipoValidacion = TipoValidacion;
            this.Usuario = Usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetJournalValidationRequest", WrapperNamespace="http://abaseguros.com", IsWrapped=true)]
    public partial class GetJournalValidationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://abaseguros.com", Order=0)]
        public ValidateAddIn.ServiceReference.GetJournalValidationDC AccountingInformation;
        
        public GetJournalValidationRequest() {
        }
        
        public GetJournalValidationRequest(ValidateAddIn.ServiceReference.GetJournalValidationDC AccountingInformation) {
            this.AccountingInformation = AccountingInformation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetJournalValidationResponse", WrapperNamespace="http://abaseguros.com", IsWrapped=true)]
    public partial class GetJournalValidationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://abaseguros.com", Order=0)]
        public ValidateAddIn.ServiceReference.GetJournalValidationCollectionDC GetJournalValidation;
        
        public GetJournalValidationResponse() {
        }
        
        public GetJournalValidationResponse(ValidateAddIn.ServiceReference.GetJournalValidationCollectionDC GetJournalValidation) {
            this.GetJournalValidation = GetJournalValidation;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidacionesSiacServiceContractChannel : ValidateAddIn.ServiceReference.ValidacionesSiacServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidacionesSiacServiceContractClient : System.ServiceModel.ClientBase<ValidateAddIn.ServiceReference.ValidacionesSiacServiceContract>, ValidateAddIn.ServiceReference.ValidacionesSiacServiceContract {
        
        public ValidacionesSiacServiceContractClient() {
        }
        
        public ValidacionesSiacServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidacionesSiacServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidacionesSiacServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidacionesSiacServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ValidateAddIn.ServiceReference.ObtieneBitacoraResponse ValidateAddIn.ServiceReference.ValidacionesSiacServiceContract.ObtieneBitacora(ValidateAddIn.ServiceReference.ObtieneBitacoraRequest request) {
            return base.Channel.ObtieneBitacora(request);
        }
        
        public ValidateAddIn.ServiceReference.ObtieneBitacoraCollectionDC ObtieneBitacora(ValidateAddIn.ServiceReference.Request_BU_Sistema_Plaza_FechaValDC Request_BU_Sistema_Plaza_FechaVal, int idTipoValidacion) {
            ValidateAddIn.ServiceReference.ObtieneBitacoraRequest inValue = new ValidateAddIn.ServiceReference.ObtieneBitacoraRequest();
            inValue.Request_BU_Sistema_Plaza_FechaVal = Request_BU_Sistema_Plaza_FechaVal;
            inValue.idTipoValidacion = idTipoValidacion;
            ValidateAddIn.ServiceReference.ObtieneBitacoraResponse retVal = ((ValidateAddIn.ServiceReference.ValidacionesSiacServiceContract)(this)).ObtieneBitacora(inValue);
            return retVal.ObtieneBitacora;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ValidateAddIn.ServiceReference.ObtieneBitacoraResponse> ValidateAddIn.ServiceReference.ValidacionesSiacServiceContract.ObtieneBitacoraAsync(ValidateAddIn.ServiceReference.ObtieneBitacoraRequest request) {
            return base.Channel.ObtieneBitacoraAsync(request);
        }
        
        public System.Threading.Tasks.Task<ValidateAddIn.ServiceReference.ObtieneBitacoraResponse> ObtieneBitacoraAsync(ValidateAddIn.ServiceReference.Request_BU_Sistema_Plaza_FechaValDC Request_BU_Sistema_Plaza_FechaVal, int idTipoValidacion) {
            ValidateAddIn.ServiceReference.ObtieneBitacoraRequest inValue = new ValidateAddIn.ServiceReference.ObtieneBitacoraRequest();
            inValue.Request_BU_Sistema_Plaza_FechaVal = Request_BU_Sistema_Plaza_FechaVal;
            inValue.idTipoValidacion = idTipoValidacion;
            return ((ValidateAddIn.ServiceReference.ValidacionesSiacServiceContract)(this)).ObtieneBitacoraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ValidateAddIn.ServiceReference.ObtieneBitacoraHistorialResponse ValidateAddIn.ServiceReference.ValidacionesSiacServiceContract.ObtieneBitacoraHistorial(ValidateAddIn.ServiceReference.ObtieneBitacoraRequest request) {
            return base.Channel.ObtieneBitacoraHistorial(request);
        }
        
        public ValidateAddIn.ServiceReference.ObtieneBitacoraCollectionDC ObtieneBitacoraHistorial(ValidateAddIn.ServiceReference.Request_BU_Sistema_Plaza_FechaValDC Request_BU_Sistema_Plaza_FechaVal, int idTipoValidacion) {
            ValidateAddIn.ServiceReference.ObtieneBitacoraRequest inValue = new ValidateAddIn.ServiceReference.ObtieneBitacoraRequest();
            inValue.Request_BU_Sistema_Plaza_FechaVal = Request_BU_Sistema_Plaza_FechaVal;
            inValue.idTipoValidacion = idTipoValidacion;
            ValidateAddIn.ServiceReference.ObtieneBitacoraHistorialResponse retVal = ((ValidateAddIn.ServiceReference.ValidacionesSiacServiceContract)(this)).ObtieneBitacoraHistorial(inValue);
            return retVal.ObtieneBitacora;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ValidateAddIn.ServiceReference.ObtieneBitacoraHistorialResponse> ValidateAddIn.ServiceReference.ValidacionesSiacServiceContract.ObtieneBitacoraHistorialAsync(ValidateAddIn.ServiceReference.ObtieneBitacoraRequest request) {
            return base.Channel.ObtieneBitacoraHistorialAsync(request);
        }
        
        public System.Threading.Tasks.Task<ValidateAddIn.ServiceReference.ObtieneBitacoraHistorialResponse> ObtieneBitacoraHistorialAsync(ValidateAddIn.ServiceReference.Request_BU_Sistema_Plaza_FechaValDC Request_BU_Sistema_Plaza_FechaVal, int idTipoValidacion) {
            ValidateAddIn.ServiceReference.ObtieneBitacoraRequest inValue = new ValidateAddIn.ServiceReference.ObtieneBitacoraRequest();
            inValue.Request_BU_Sistema_Plaza_FechaVal = Request_BU_Sistema_Plaza_FechaVal;
            inValue.idTipoValidacion = idTipoValidacion;
            return ((ValidateAddIn.ServiceReference.ValidacionesSiacServiceContract)(this)).ObtieneBitacoraHistorialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ValidateAddIn.ServiceReference.ObtieneBitacoraResponse ValidateAddIn.ServiceReference.ValidacionesSiacServiceContract.ObtieneBitacoraCargaReporte(ValidateAddIn.ServiceReference.ObtieneBitacoraReporteRequest request) {
            return base.Channel.ObtieneBitacoraCargaReporte(request);
        }
        
        public ValidateAddIn.ServiceReference.ObtieneBitacoraCollectionDC ObtieneBitacoraCargaReporte(int BusinessUnit, System.DateTime Fecha, int TipoArchivo, int TipoValidacion, string Usuario) {
            ValidateAddIn.ServiceReference.ObtieneBitacoraReporteRequest inValue = new ValidateAddIn.ServiceReference.ObtieneBitacoraReporteRequest();
            inValue.BusinessUnit = BusinessUnit;
            inValue.Fecha = Fecha;
            inValue.TipoArchivo = TipoArchivo;
            inValue.TipoValidacion = TipoValidacion;
            inValue.Usuario = Usuario;
            ValidateAddIn.ServiceReference.ObtieneBitacoraResponse retVal = ((ValidateAddIn.ServiceReference.ValidacionesSiacServiceContract)(this)).ObtieneBitacoraCargaReporte(inValue);
            return retVal.ObtieneBitacora;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ValidateAddIn.ServiceReference.ObtieneBitacoraResponse> ValidateAddIn.ServiceReference.ValidacionesSiacServiceContract.ObtieneBitacoraCargaReporteAsync(ValidateAddIn.ServiceReference.ObtieneBitacoraReporteRequest request) {
            return base.Channel.ObtieneBitacoraCargaReporteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ValidateAddIn.ServiceReference.ObtieneBitacoraResponse> ObtieneBitacoraCargaReporteAsync(int BusinessUnit, System.DateTime Fecha, int TipoArchivo, int TipoValidacion, string Usuario) {
            ValidateAddIn.ServiceReference.ObtieneBitacoraReporteRequest inValue = new ValidateAddIn.ServiceReference.ObtieneBitacoraReporteRequest();
            inValue.BusinessUnit = BusinessUnit;
            inValue.Fecha = Fecha;
            inValue.TipoArchivo = TipoArchivo;
            inValue.TipoValidacion = TipoValidacion;
            inValue.Usuario = Usuario;
            return ((ValidateAddIn.ServiceReference.ValidacionesSiacServiceContract)(this)).ObtieneBitacoraCargaReporteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ValidateAddIn.ServiceReference.GetJournalValidationResponse ValidateAddIn.ServiceReference.ValidacionesSiacServiceContract.GetJournalValidation(ValidateAddIn.ServiceReference.GetJournalValidationRequest request) {
            return base.Channel.GetJournalValidation(request);
        }
        
        public ValidateAddIn.ServiceReference.GetJournalValidationCollectionDC GetJournalValidation(ValidateAddIn.ServiceReference.GetJournalValidationDC AccountingInformation) {
            ValidateAddIn.ServiceReference.GetJournalValidationRequest inValue = new ValidateAddIn.ServiceReference.GetJournalValidationRequest();
            inValue.AccountingInformation = AccountingInformation;
            ValidateAddIn.ServiceReference.GetJournalValidationResponse retVal = ((ValidateAddIn.ServiceReference.ValidacionesSiacServiceContract)(this)).GetJournalValidation(inValue);
            return retVal.GetJournalValidation;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ValidateAddIn.ServiceReference.GetJournalValidationResponse> ValidateAddIn.ServiceReference.ValidacionesSiacServiceContract.GetJournalValidationAsync(ValidateAddIn.ServiceReference.GetJournalValidationRequest request) {
            return base.Channel.GetJournalValidationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ValidateAddIn.ServiceReference.GetJournalValidationResponse> GetJournalValidationAsync(ValidateAddIn.ServiceReference.GetJournalValidationDC AccountingInformation) {
            ValidateAddIn.ServiceReference.GetJournalValidationRequest inValue = new ValidateAddIn.ServiceReference.GetJournalValidationRequest();
            inValue.AccountingInformation = AccountingInformation;
            return ((ValidateAddIn.ServiceReference.ValidacionesSiacServiceContract)(this)).GetJournalValidationAsync(inValue);
        }
    }
}
